title: Luca Wehrstedt
email: luca.wehrstedt@gmail.com
description: >-
    Things and stuff...
baseurl: ""
url: "https://lw.dev"
twitter_username: LucaWehrstedt
github_username: lw
linkedin_username: lcw
# google_plus_username: LucaWehrstedt
facebook_username: luca.wehrstedt

google_analytics: "UA-109195577-1"
disqus:
    shortname: lerks

markdown: kramdown
theme: minima
timezone: "Europe/Paris"
plugins:
    - jekyll-feed
    # - jekyll-redirect-from
    # - jekyll-seo-tag
    # - jekyll-sitemap
    # - jekyll-avatar
    # - jemoji
    # - jekyll-mentions
    # - jekyll-include-cache
